# --- Server Configuration ---
server.port=8080

# --- File Upload Limits (10MB) ---
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# --- Database (PostgreSQL) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=create

# --- S3 Storage Configuration ---
# If using Cloudflare R2, the endpoint looks like: https://<ACCOUNT_ID>.r2.cloudflarestorage.com
# If using MinIO (Local), use: http://localhost:9000
spring.cloud.aws.region.static=${S3_REGION:us-east-1}
spring.cloud.aws.credentials.access-key=${S3_ACCESS_KEY:minioadmin}
spring.cloud.aws.credentials.secret-key=${S3_SECRET_KEY:minioadmin}
spring.cloud.aws.s3.endpoint=${S3_ENDPOINT_LOCAL:http://localhost:9000}
spring.cloud.aws.s3.path-style-access-enabled=true

aws.s3.bucket=${S3_BUCKET_NAME:my-pastebin-bucket}
# --- JWT Token Info (NEVER commit these to Git!) ---
jwt.secret-key=${JWT_SECRET_KEY}
jwt.expiration = ${JWT_EXPIRATION_TIME}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}